### ISSUE TITLE
it doesn't generate xml when some tests fail

### ISSUE THREAD

**Issue by tchalamarla** [rustation/cargo-test-junit#3]
when a test failed with panic or assert it doesn't generate any xml

i thought it is supposed to generate pass fail for tests.

will it only work if all tests pass?

**Comment by jgrund** [comment]
@tchalamarla published an update, can you try again?

**Comment by tchalamarla** [comment]
sorry for the delayed response.

it seems to be generating report with proper fail and pass case now
